User update
dam2-intermodular/api pull request #6
Opened 2024-01-31 19:09 UTC by DoomMaGeddon

feat: added PUT for /users
fix: fixed data sent to database

2024-01-31 19:26 UTC, TortitasT requested changes
cambiosss

2024-01-31 19:26 UTC, TortitasT commented on tests/users.test.ts
> +  test("should update user", async () => {
Se llama should update user pero esperamos un error 400 en el expect

2024-01-31 19:26 UTC, TortitasT commented on src/http/controllers/users/update.ts
> +                    body
aqui en vez de { body } seria solo body creo

2024-01-31 19:26 UTC, TortitasT commented on src/http/controllers/users/update.ts
> +                user: createResourceFromDocument(user!!, UserResourceSchema),
que es el `user!!` ?

2024-01-31 19:26 UTC, TortitasT commented on src/http/controllers/users/update.ts
> +            if (body.password !== undefined && body.password !== null)
habría que comprobar cual es el valor de body.password cuando no esta rellenado y hacer el if con ese valor en vez de con undefined y null.

2024-01-31 19:26 UTC, TortitasT commented on src/http/controllers/users/update.ts
> +            const hashedPassword = await Bun.password.hash(body.password);
el hashedPassword habria que meterlo dentro del if de abajo, de esta forma no se hashea (que sale caro en cpu) siempre y solo cuando se rellena el password

2024-01-31 19:26 UTC, TortitasT commented on tests/users.test.ts
> +});
Yo metería otro test que creara un usuario y comprobara que se puede actualizar.

2024-01-31 21:25 UTC, DoomMaGeddon commented on src/http/controllers/users/update.ts
> +                user: createResourceFromDocument(user!!, UserResourceSchema),
Es para idicar que "user" no tiene posibilidad de ser null, ya que por defecto sale un warning de que puede ser null.

2024-01-31 21:45 UTC, DoomMaGeddon commented on tests/users.test.ts
> +  test("should update user", async () => {
Arreglado

2024-01-31 21:45 UTC, DoomMaGeddon commented on src/http/controllers/users/update.ts
> +                    body
Arreglado

2024-01-31 22:06 UTC, DoomMaGeddon commented on src/http/controllers/users/update.ts
> +            const hashedPassword = await Bun.password.hash(body.password);
Cierto, arreglado

2024-01-31 22:07 UTC, DoomMaGeddon commented on tests/users.test.ts
> +});
Añadido

2024-01-31 22:10 UTC, DoomMaGeddon commented on src/http/controllers/users/update.ts
> +            if (body.password !== undefined && body.password !== null)
Hecho

2024-01-31 22:11 UTC, TortitasT commented on src/http/controllers/users/update.ts
> +                user: createResourceFromDocument(user!!, UserResourceSchema),
puede ser que cuando eso sea null sera porque no lo ha encontrado, quizas en vez de !! deberia haber un if comprobando si es null y si es el caso devolver un 404. Asi a primera vista me parece que como esta ahora si le pasas un id q no existe al endpoint daria una excepcion.

2024-01-31 22:13 UTC, DoomMaGeddon commented on src/http/controllers/users/update.ts
> +                user: createResourceFromDocument(user!!, UserResourceSchema),
La cosa es que en teoría, este método sería utilizado únicamente cuando sabemos el usuario que queremos actualizar, por lo que debe existir: ya sea un usuario cambiando sus propios datos desde su perfil, o un administrador cambiando los usuarios recibidos y listados por un GET.

2024-02-01 07:59 UTC, TortitasT commented on src/http/controllers/users/update.ts
> +                user: createResourceFromDocument(user!!, UserResourceSchema),
si eso seguro, pero en una api tenemos que protegernos de lo que nos puedan mandar mal, si da una excepcion devolverá un 500 y los 500 solo deberian ocurrir cuando algo pete y tengamos que arreglarlo. perdon por el coñazo eh sjsjj

2024-02-01 14:42 UTC, DoomMaGeddon commented on src/http/controllers/users/update.ts
> +                user: createResourceFromDocument(user!!, UserResourceSchema),
Sin problema jajaja, razón tienes. Voy a arreglarlo

2024-02-01 15:47 UTC, merged